apiVersion: v1
kind: ConfigMap
metadata:
  name: hash-config
  namespace: exercises
data:
  MESSAGE: "hello world"
  PONG_SERVICE_URL: "http://localhost:5001/pings"
  
  information.txt: |
    this text is from file

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-db-init
  namespace: exercises
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS lines (
        id SERIAL PRIMARY KEY,
        content TEXT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );