apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-count-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestcount
  template:
    metadata:
      labels:
        app: requestcount
    spec:
      volumes:
        - name: text
          configMap:
            name: hash-config
            items:
            - key: "information.txt"
              path: "information.txt"
      containers:
        - name: pingpong
          image: ping-pong:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_FILE_PATH
              value: "/usr/src/app/files/pong.log"
            - name: PG_ADDR
              value: "postgres://stac:password@postgres-svc/pingpong?sslmode=disable"
        - name: hashreader
          image: hash-reader:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FILE_PATH
              value: "/usr/src/app/files/information.txt"
            - name: PONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: hash-config
                  key: PONG_SERVICE_URL
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hash-config
                  key: MESSAGE
          volumeMounts:
            - name: text
              mountPath: /usr/src/app/files
              readOnly: true