apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-count-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestcount
  template:
    metadata:
      labels:
        app: requestcount
    spec:
      volumes:
        - name: shared-hash
          persistentVolumeClaim:
            claimName: hash-claim
      containers:
        - name: pingpong
          image: ping-pong:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-hash
            mountPath: /usr/src/app/files
          env:
            - name: LOG_FILE_PATH
              value: "/usr/src/app/files/pong.log"
        - name: hashreader
          image: hash-reader:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PONG_SERVICE_URL
              value: "http://ping-pong-svc:2453/pings"