apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/namespace.yml
- manifest/configMap.yml
- manifest/secret.yml
- manifest/db-init-job.yml
- manifest/statefulset.yml
- manifest/analysistemplate.yml
- manifest/rollout.yml
- manifest/service.yml
- manifest/ingress.yml
images:
- name: stacvirus/hash-reader
  newName: stacvirus/hash-reader
  newTag: 1.0.0
- name: stacvirus/ping-pong
  newTag: fbbecec25abb80e221b9c82cf1f3156f8d46a988
