apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest/namespace.yml
  - manifest/storageclassname.yml
  - manifest/persistentvolume.yml
  - manifest/persistentvolumeclaim.yml
  - manifest/statefulset.yml
  - manifest/configMap.yml
  - manifest/analysistemplate.yml
  - manifest/rollout.yml
  - manifest/service.yml
  - manifest/ingress.yml
images:
  - name: ping-pong
    newName: ping-pong
    newTag: 1.0.0
  - name: hash-reader
    newName: hash-reader
    newTag: 1.0.0