apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest/namespace.yml
  - manifest/statefulset.yml
  - manifest/configmap.yml
  - manifest/deployment.yml
  - manifest/service.yml
  - manifest/ingress.yml