apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yml
  - ./../../base

patches:
  - path: configmap.yml
  - path: broadcast-deployment.yml
  - path: db-init.yml

namePrefix: prod-

images:
  - name: stacvirus/broadcast
    newTag: 27044f489379e99c4fdf14068bdde6cb2e7b1ffb
  - name: stacvirus/todo-app
    newTag: 27044f489379e99c4fdf14068bdde6cb2e7b1ffb
  - name: stacvirus/todo-backend
    newTag: 27044f489379e99c4fdf14068bdde6cb2e7b1ffb