apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:

images:
  - name: stacvirus/broadcast
    newTag: 3675d498c1bab5a6f00fd5a81222dde9f4c0243f
  - name: stacvirus/todo-app
    newTag: 3675d498c1bab5a6f00fd5a81222dde9f4c0243f
  - name: stacvirus/todo-backend
    newTag: 3675d498c1bab5a6f00fd5a81222dde9f4c0243f