apiVersion: v1
kind: Service
metadata:
  name: hashes-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: hashes
  ports:
    - port: 2245
      protocol: TCP
      targetPort: 5000