apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: greeter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 2020
            initialDelaySeconds: 15
            periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
    spec:
      containers:
        - name: greeter
          image: greeter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 2020
            initialDelaySeconds: 15
            periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-reader-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-reader
  template:
    metadata:
      labels:
        app: hash-reader
    spec:
      volumes:
        - name: text
          configMap:
            name: hash-config
            items:
            - key: "information.txt"
              path: "information.txt"
      containers:
        - name: hashreader
          image: hash-reader:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: FILE_PATH
              value: "/usr/src/app/files/information.txt"
            - name: PONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: hash-config
                  key: PONG_SERVICE_URL
            - name: GREETER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: hash-config
                  key: GREETER_SERVICE_URL
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hash-config
                  key: MESSAGE
          volumeMounts:
            - name: text
              mountPath: /usr/src/app/files
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ping-pong:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: LOG_FILE_PATH
              value: "/usr/src/app/files/pong.log"
            - name: PG_ADDR
              value: "postgres://stac:password@postgres-svc/pingpong?sslmode=disable"
          readinessProbe:
            httpGet:
              path: /pings
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /pings
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 5