apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:

images:
  - name: stacvirus/broadcast
    newTag: 1.0.0
  - name: stacvirus/todo-app
    newTag: 1.0.0
  - name: stacvirus/todo-backend
    newTag: 1.0.0