apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/configmap.yml
- manifest/secret.yml
- manifest/db-init-job.yml
- manifest/statefulset.yml
- manifest/deployment.yml
- manifest/service.yml
- manifest/gateway.yml
- manifest/httproute.yml