apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: project
data:
  CACHE_FILE_PATH: "/usr/src/app/data"
  BACKEND_URL: "http://localhost:8081/todos"
  PG_ADDR: "postgres://stac:password@postgres-svc/todo?sslmode=disable"
  NATS_URL: "nats://my-nats.default.svc.cluster.local:4222"
  NATS_USER: "nats_client"
  NATS_PASSWORD: "rJ9zAC764i"
  NATS_SUBJECT: "todo.operations"
  TELEGRAM_BOT_TOKEN: "your_telegram_bot_token"
  TELEGRAM_CHAT_ID: "your_telegram_chat_id"