apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: todo-app:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: todoapp-storage
            mountPath: /usr/src/app/data
          env:
            - name: CACHE_FILE_PATH
              value: "/usr/src/app/data"