apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: todo-app:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: todoapp-storage
            mountPath: /usr/src/app/data
          envFrom:
            - configMapRef:
                name: todo-config
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: todo-config