apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: todo-app:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: todoapp-storage
            mountPath: /usr/src/app/data
          env:
            - name: CACHE_FILE_PATH
              value: "/usr/src/app/data"
            - name: BACKEND_URL
              value: "http://localhost:8081/todos"
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent