apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: todo-app:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: todoapp-storage
            mountPath: /usr/src/app/data
          envFrom:
            - configMapRef:
                name: todo-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 8000
        - name: todo-backend
          image: todo-backend:1.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: todo-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
  namespace: project
spec:
  replicas: 10
  selector:
    matchLabels:
      app: broadcast
  template:
    metadata:
      labels:
        app: broadcast
    spec:
      containers:
        - name: broadcast
          image: broadcast:0.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: todo-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8585
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 8585