apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - port: 2245
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: project
  labels:
    app: postgres
spec:
  ports: 
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgresapp

---
apiVersion: v1
kind: Service
metadata:
  name: broadcast-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: broadcast
  ports:
    - port: 8585
      protocol: TCP
      targetPort: 8585