apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - port: 2245
      protocol: TCP
      targetPort: 8080