apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/namespace.yml
- manifest/deployment.yml
- manifest/service.yml
- manifest/ingress.yml
images:
- name: hash-generator
  newName: hash-generator
  newTag: 1.0.0
- name: hash-reader
  newName: hash-reader
  newTag: 1.0.0
- name: stacvirus/hash-reader
  newTag: ed1550eec849b3b8615f19ac64ffd55f1d9b45dc
