name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backends
        run: |-
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${GITHUB_SHA} ./todo-app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${GITHUB_SHA}
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${GITHUB_SHA} ./todo-backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${GITHUB_SHA}
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/broadcast:${GITHUB_SHA} ./broadcast
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/broadcast:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image for todo-app
        working-directory: ./todo-app/manifest/overlays/staging
        run: kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:$GITHUB_SHA

      - name: Use right image for todo-backend
        working-directory: ./todo-app/manifest/overlays/staging
        run: kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:$GITHUB_SHA

      - name: Use right image for broadcast
        working-directory: ./todo-app/manifest/overlays/staging
        run: kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/broadcast:$GITHUB_SHA

      - name: commit kustomization.yml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            todo-app/manifest/overlays/staging/kustomization.yml
          message: "chore: update image tags to ${{ github.sha }}"