name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backends
        run: |-
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:${GITHUB_SHA} ./ping-pong
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:${GITHUB_SHA}
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/hash-reader:${GITHUB_SHA} ./hash-reader
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hash-reader:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image for ping-pong
        working-directory: ./ping-pong
        run: kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:$GITHUB_SHA

      - name: Use right image for hash-reader
        working-directory: ./hash-reader
        run: kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/hash-reader:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            ping-pong/kustomization.yaml
            hash-reader/kustomization.yaml
          message: "chore: update image tags to ${{ github.sha }}"